# Generated by Django 3.0.4 on 2022-03-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_braintree_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='braintree_id',
            new_name='transaction_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='paid',
            new_name='verified',
        ),
        migrations.AddField(
            model_name='order',
            name='ref',
            field=models.CharField(default=False, max_length=200),
        ),
    ]
