# Generated by Django 3.0.4 on 2022-04-03 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(choices=[('Kano', 'Kano')], default='Kano', max_length=100),
        ),
    ]
