# Generated by Django 3.0.4 on 2022-04-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20220403_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(choices=[('DALA', 'DALA'), ('FAGGE', 'FAGGE'), ('KANO MUNICIPAL', 'KANO MUNICIPAL'), ('KUMBOTSO', 'KUMBOTSO'), ('NASSARAWA', 'NASSARAWA'), ('RIMI', 'RIMI'), ('TARAUNI', 'TARAUNI'), ('UNGOGO', 'UNGOGO')], default='NASSARAWA', max_length=100),
        ),
    ]
